version: '3.3'

services:
  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'tinder_admin'
      POSTGRES_PASSWORD: 'pg123'
    ports:
      - '5432:5432'